"""
TwinStore設定モジュール

設定値と定数の管理を行う
"""

from .constants import (
    QUALITY_CONSTANTS,
    TIME_SERIES_CONSTANTS, 
    STATISTICS_CONSTANTS,
    PREDICTION_CONSTANTS,
    SCORE_WEIGHTS,
    PERFORMANCE_CONSTANTS,
    PLOT_CONSTANTS,
    ERROR_MESSAGES
)
from .defaults import (
    PREDICTOR_DEFAULTS,
    PREPROCESSOR_DEFAULTS,
    QUALITY_CHECKER_DEFAULTS,
    ANOMALY_DETECTOR_DEFAULTS,
    PIPELINE_DEFAULTS,
    EXPLAINER_DEFAULTS,
    INDUSTRY_PRESETS,
    DATA_FORMAT_DEFAULTS,
    LOADER_DEFAULTS,
    REPORT_DEFAULTS,
    API_DEFAULTS,
    LOGGING_DEFAULTS
)
from .validation import (
    DATA_TYPE_RULES,
    DATA_VOLUME_RULES,
    MISSING_VALUE_RULES,
    ANOMALY_RULES,
    TIME_SERIES_RULES,
    STORE_ATTRIBUTE_RULES,
    PREDICTION_VALIDATION_RULES,
    VALIDATION_MESSAGES,
    VALIDATION_RULES,
    get_validation_rule,
    get_validation_message
)
from .visualization import (
    PLOT_DEFAULTS,
    COLOR_PALETTES,
    PLOT_TYPE_CONFIGS,
    PLOTLY_DEFAULTS,
    DASHBOARD_CONFIG,
    ANIMATION_CONFIG,
    EXPORT_CONFIG,
    JAPANESE_FONT_CONFIG,
    THEMES,
    VISUALIZATION_LIMITS
)

__all__ = [
    # constants.py
    'QUALITY_CONSTANTS',
    'TIME_SERIES_CONSTANTS',
    'STATISTICS_CONSTANTS',
    'PREDICTION_CONSTANTS',
    'SCORE_WEIGHTS',
    'PERFORMANCE_CONSTANTS',
    'PLOT_CONSTANTS',
    'ERROR_MESSAGES',
    
    # defaults.py
    'PREDICTOR_DEFAULTS',
    'PREPROCESSOR_DEFAULTS',
    'QUALITY_CHECKER_DEFAULTS',
    'ANOMALY_DETECTOR_DEFAULTS',
    'PIPELINE_DEFAULTS',
    'EXPLAINER_DEFAULTS',
    'INDUSTRY_PRESETS',
    'DATA_FORMAT_DEFAULTS',
    'LOADER_DEFAULTS',
    'REPORT_DEFAULTS',
    'API_DEFAULTS',
    'LOGGING_DEFAULTS',
    
    # validation.py
    'DATA_TYPE_RULES',
    'DATA_VOLUME_RULES',
    'MISSING_VALUE_RULES',
    'ANOMALY_RULES',
    'TIME_SERIES_RULES',
    'STORE_ATTRIBUTE_RULES',
    'PREDICTION_VALIDATION_RULES',
    'VALIDATION_MESSAGES',
    'VALIDATION_RULES',  # 後方互換性のため
    'get_validation_rule',
    'get_validation_message',
    
    # visualization.py
    'PLOT_DEFAULTS',
    'COLOR_PALETTES',
    'PLOT_TYPE_CONFIGS',
    'PLOTLY_DEFAULTS',
    'DASHBOARD_CONFIG',
    'ANIMATION_CONFIG',
    'EXPORT_CONFIG',
    'JAPANESE_FONT_CONFIG',
    'THEMES',
    'VISUALIZATION_LIMITS',
]